const alltypes ={
'enterprise':{ 'name': 'enterprise', group:'Enterprise', children: ['platformtype','component','componentendpointtype','role','user','workitemtype','status', 'componentenvironment','organization'], init: [{_id:1, name: 'Company' }]},
'component':{'name': 'component' , group:'Enterprise', children: ['componentendpoint' ], coload:{ 'platformType':'platformtype','buildType':'buildtype','scmType':'scmtype'}, init :[{_id:1, enterpriseId: 1 , platformTypeId:1, name:'Component', scmTypeId:1, scmUrl:'https://example.com/repo1', buildTypeId: 1, artifactGroupId:'com.company', platformGroup:'example cloud'}]}, 
'platformtype':{'name': 'platformType', group:'Enterprise', init:[{ _id:1, enterpriseId: 1, name: 'AWS - EKS'} ]}, 
'componentendpoint':{'name': 'componentEndpoint', group:'Enterprise', coload:{'componentEndpointType':'componentendpointtype'}, init:[{ _id:1, componentId: 1, name: '/api/post', componentEndpointTypeId: 1}]},
'componentendpointtype':{'name': 'componentEndpointType', group:'Enterprise', init:[{_id:1, enterpriseId:1, name: 'REST API'} ]},
'componentenvironment': {'name': 'componentEnvironment', group: 'Enterprise', init:[{_id:1, componentId:1, environmentId:1}]},
'environment':	{'name': 'environment', group:'Enterprise', init:[{_id:1, enterpriseId:1, name:'Dev', production:false} ]},
'buildtype': {'name': 'buildType', group: 'Enterprise', init:[{_id:1, enterpriseId:1, name:'Maven-Java'}]},
'scmtype': {'name': 'scmType', group: 'Enterprise', init:[{_id:1, enterpriseId:1, name:'GitHub'}]},
'role':{'name': 'role', group:'Enterprise' ,init:[{_id:1, enterpriseId:1, name:'Admin' }]},
'user':{'name': 'user', group:'Enterprise', init:[{_id:1, enterpriseId:1, name:'Joe User' }, {_id:2, enterpriseId:1, name:'Alice User'}]},
'workitemtype':{'name': 'workItemType', group:'Enterprise' , init:[{ _id:1, enterpriseId:1, name:'Epic', keyPrefix:'EPIC'}, {_id:2, enterpriseId:1, name:'Feature',keyPrefix:'FEAT'},{_id:3, enterpriseId:1, name:'Story', keyPrefix:'ST'}]}, 
'status':{'name': 'status', group:'Enterprise' , init:[{_id:1, enterpriseId:1,  name:'Open'}, {_id:2, enterpriseId:1, name:'In Progress'},{_id:3, enterpriseId:1, name:'Done'}]},
'eventtype':{'name': 'eventType',  group:'Enterprise' , init:[{_id:1, name:'Build'},{_id:2, name:'Deploy'}]},
'organization':{'name': 'organization', group:'Organization', children:['workinggroup','rollup', 'securitygroup','allowedworkitemtype'], recursive:'parentOrganizationId', init:[{_id:1, name:'Example', enterpriseId: 1, parentOrganizationId: null},{_id:2, name:'Example - sub', enterpriseId: 1, parentOrganizationId: 1}]},
'securitygroup':{'name': 'securityGroup', group:'Organization', init:[{_id:1, name:'Admin', roleId:1, organizationId: 1}]},
'allowedworkitemtype':{'name': 'allowedWorkItemType', group:'Organization', coload:{'workItemType':'workitemtype'}, init:[{_id:1, workItemTypeId:1, organizationId: 1, workflowId:1}, {_id:2, workItemTypeId:2, organizationId:2, workflowId:1}]},
'actual':{'name': 'actual', group:'Organization', init:[{_id:1, amount:0.01, rollupId: 1, timestamp:'2020-01-01T12:00:00.000'}]},
'workinggroup':{'name': 'workingGroup', group:'Organization', children: ['workinggroupmember'],init:[{_id:1, organizationId:1, name:'Executive'}]},
'workinggroupmember': {'name': 'workingGroupMember', group: 'Organization', coload:{'user':'user'}, init: [{_id:1, workingGroupId: 1, userId: 1}]},
'rollup':{'name': 'rollup', group:'Organization', children:[ 'actual','increment'], init:[{_id:1, organizationId:1,  name:'2020 Budget', start:'2020-01-01T00:00:00.000', end:'2020-12-31T23:59:59.999', budget:0.01}, {_id:2, organizationId:1,  name:'2021 Budget', start:'2021-01-01T00:00:00.000', end:'2021-12-31T23:59:59.999', budget:0.01}]},
'increment':{'name': 'increment', group:'Organization', children:['period'], init:[{_id:1, name: 'Q1', rollupId:1}]},
'period':{'name': 'period', group:'Organization', init:[{_id:1, incrementId:1, name: 'Sprint 1',start:'2020-01-01T00:00:00.000',end:'2020-01-14T23:59:59.999'}]},
'workitem':{'name': 'workItem', group: 'WorkItem', isLarge:true, children:['workitemhistory','workitemcomment','workitemattachment','workitemcomponent','workitemlink'], coload:{'period':'period', 'createdByUser':'user', 'lastUpdatedUser':'user', 'assignedToUser':'user' }, recursive:'parentWorkItemId', init:[{_id:1, itemKey:'EPIC-1',summary:'Super Duper Epic',description:'The most important work ever conceived by humanity. God Himself is pleased.', estimate:1, currentStepId:2, periodId:1, workflowId:1, organizationId:1, workingGroupId:1, createdByUserId: 1, assignedToUserId:1, parentWorkItemId:null, workItemTypeId:1, created: '2020-01-02T13:01:00.000', lastUpdated:'2020-01-02T14:00:00.000', lastUpdatedUserId:2}, {_id:2, itemKey:'EPIC-2',summary:'Example',description:'Work Description', estimate:1, currentStepId:1, periodId:1, organizationId:1, workflowId:1, workingGroupId:1, createdByUserId: 2, assignedToUserId:2, parentWorkItemId:null, workItemTypeId:1,created: '2021-01-02T13:01:00.000', lastUpdated:'2021-01-02T14:00:00.000', lastUpdatedUserId:2}]},
'workitemhistory':{'name': 'workItemHistory', group: 'WorkItem', init:[{_id:1, workItemId:1, date:'2020-01-01T12:00:00.000', changeDetail:'something changed'}]},
'workitemlink': {'name': 'workItemLink', group: 'WorkItem', coload: {'workItemLinkType':'workitemlinktype'}, init: [{_id:1, workItemId: 1, linkedWorkItemId:2, workItemLinkTypeId:1}]},
'workitemlinktype': {'name': 'workItemLinkType', group: 'WorkItem', init: [{_id: 1, name: 'Depends on'}, {_id: 2, name: 'Blocked by'}]},
'workitemattachment':{'name': 'workItemAttachment', group: 'WorkItem', init:[{_id:1, name:'picture.jpg', workItemId:1, location:'https://storageloc/picture.jpg'}]},
'workitemcomment':{'name': 'workItemComment', group: 'WorkItem', init:[{_id:1, workItemId:1 , comment:'best epic ever!', date:'2020-01-01T12:01:00.000',userId:1}]},
'workitemcomponent': {'name': 'workItemComponent', group: 'WorkItem', coload: {'component':'component'}, init:[{_id:1, workItemId:1, componentId: 1}]},
'workitemevent': {'name':'workItemComment', group:'WorkItem', coload:{'eventType':'eventtype'}, init:[{_id:1, workItemId:1, eventTypeId:1}]},
'workflow':{'name':'workflow', group:'Workflow', children:['step'], init:[{_id:1, name: 'Kanban'},{_id:2, name:'Scrum' }]},
'step':{'name': 'step', group:'Workflow', children:['transition','steprole'], coload:{'status':'status'}, init:[{_id:1, workflowId:1, name:  'To Do', isInitial:true, statusId:1, sortOrder:1}, {_id:2, workflowId:1, name:'In Progress', statusId:2, isInitial:false, sortOrder:2}, {_id:3, workflowId:1, name:'Done', statusId:3, isInitial:false, sortOrder:3}]},
'steprole':{'name': 'stepRole', group:'Workflow', coload:{'role':'role'}, init:[{_id:1, stepId: 1, roleId: 1}, {_id:2, stepId: 2, roleId: 1}, {_id:3, stepId: 3, roleId: 1}]},
'transition':{'name': 'transition', group:'Workflow', children:['transitioncondition','posttransitionevent'], init:[{_id:1, name: 'In Progress', stepId:1, toStepId:2},{_id:2, name:'Done', stepId:2, toStepId:3},{_id:3, name:'Back to In Progress', stepId:3, toStepId:2}, {_id:4, name: 'Back to To Do', stepId:2, toStepId:1}]},
'transitioncondition':{'name': 'transitionCondition', group:'Workflow', init:[{_id:1, field: 'workItem.estimate', value:'null', evaluator:'!=', transitionId:1}]},
'posttransitionevent':{'name': 'postTransitionEvent', group: 'Workflow',  init:[{_id:1, transitionId:3, url:'https://example.com/api/deploy', parameters:'name={workItem.workItemComponents.component.scmUrl&id={workItem._id'}]},
'association':{'name': 'association', children:['associationorganization'], group:'Association', init:[{_id:1, enterpriseId:1, name: 'Grouping'}]},
'associationorganization':{'name': 'associationOrganization', group:'AssociationOrganization', coload:{'organization':'organization'}, init:[{_id:1, associationId:1, organizationId:1}, {_id:2, associationId:1, organizationId:2}]}		 
}

module.exports =alltypes;